# These are supported funding model platforms

ko_fi: dolezsa # Replace with a single Ko-fi username
custom: ['https://paypal.me/dolezsa'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
